# Generated by Django 4.1 on 2023-12-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USER'), (1, 'SUPERADMIN'), (2, 'COMPLAIN REVIEWER')], default=1),
        ),
    ]
