# Generated by Django 4.1 on 2023-12-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplainSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.complaincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=20)),
                ('complain_title', models.CharField(max_length=300)),
                ('complain_description', models.TextField()),
                ('complain_image', models.ImageField(upload_to='')),
                ('provience', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=2)),
                ('municipality', models.CharField(max_length=20)),
                ('ward_no', models.CharField(max_length=5)),
                ('tole', models.CharField(max_length=30, null=True)),
                ('complain_status', models.PositiveBigIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Responsed')])),
                ('complain_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.complaincategory')),
                ('complain_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.complainsubcategory')),
            ],
        ),
    ]
