# Generated by Django 4.1 on 2023-12-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainbroadcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
