# Generated by Django 4.1 on 2023-12-07 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplain',
            fields=[
                ('complain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.complain')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
            ],
            bases=('management.complain',),
        ),
        migrations.AddField(
            model_name='complain',
            name='complain_available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complain',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_complains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='management.complaincategory'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complain_sub_category', to='management.complainsubcategory'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_description', models.TextField()),
                ('response_image', models.ImageField(null=True, upload_to='')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='management.complain')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('communication_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_communication', to='management.complain')),
            ],
        ),
    ]
