# Generated by Django 4.1 on 2023-12-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_complainbroadcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='broad_category',
        ),
        migrations.DeleteModel(
            name='ComplainBroadCategory',
        ),
    ]
