# Generated by Django 4.1 on 2023-12-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_anonymouscomplain_complain_complain_available_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousComplain',
        ),
    ]
