# Generated by Django 4.1 on 2023-12-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_delete_anonymouscomplain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='is_anonymous',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.anonymouscomplain'),
        ),
    ]
