# Generated by Django 4.1 on 2023-12-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_complainbroadcategory_complain_broad_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaincategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
