# Generated by Django 4.1 on 2023-12-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_name_complaincategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
