# Generated by Django 4.1 on 2023-12-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_complain_is_anonymous_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='abc', max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='is_anonymous',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.anonymouscomplain'),
        ),
    ]
