# Generated by Django 4.1 on 2023-12-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_anonymouscomplain_complain_is_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='provience',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_status',
            field=models.PositiveBigIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Responsed')], default=1),
        ),
    ]
