# Generated by Django 4.1 on 2023-12-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_provience_complain_province_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnonymousComplain',
            new_name='AnonymousUser',
        ),
    ]
