# Generated by Django 4.1 on 2023-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_complain_complain_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='admin_message',
        ),
        migrations.AddField(
            model_name='complaincategory',
            name='nepali_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
