# Generated by Django 4.1 on 2023-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_complain_admin_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainsubcategory',
            name='nepali_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
