# Generated by Django 4.1 on 2023-12-08 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0008_rename_anonymouscomplain_anonymoususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_available', to=settings.AUTH_USER_MODEL),
        ),
    ]
