# Generated by Django 4.1 on 2023-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_complain_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_secrecy',
            field=models.PositiveBigIntegerField(choices=[(1, 'Normal'), (2, 'Urgent'), (3, 'Very Urgent')], default=1),
        ),
    ]
