# Generated by Django 4.1 on 2023-12-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nepalmap', '0005_municipality'),
        ('management', '0009_complainsubcategory_nepali_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complain_district', to='nepalmap.district'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complain_municipality', to='nepalmap.municipality'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complain_province', to='nepalmap.province'),
        ),
    ]
