# Generated by Django 4.1 on 2023-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_complain_complain_secrecy'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_priority',
            field=models.PositiveBigIntegerField(choices=[(1, 'Normal'), (2, 'Urgent'), (3, 'Very Urgent')], default=1),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_secrecy',
            field=models.BooleanField(default=False),
        ),
    ]
