# Generated by Django 4.1 on 2023-12-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_complain_district_alter_complain_municipality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='complainsubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='complainsubcategory',
            name='category',
            field=models.ManyToManyField(null=True, related_name='complainsubcategories', to='management.complaincategory'),
        ),
    ]
