# Generated by Django 4.1 on 2023-12-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_complain_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainsubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='complaincategory',
            name='category',
            field=models.ManyToManyField(related_name='complainsubcategories', to='management.complainsubcategory'),
        ),
    ]
