# Generated by Django 4.1 on 2023-12-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_complain_complain_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainsubcategories', to='management.complaincategory'),
        ),
    ]
