# Generated by Django 4.1 on 2023-12-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_complainsubcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaincategory',
            old_name='category',
            new_name='sub_category',
        ),
    ]
