# Generated by Django 4.1 on 2023-12-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_complainsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='communication',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
