# Generated by Django 4.1 on 2023-12-21 06:05

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_category_complaincategory_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='ticket_no',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
