# Generated by Django 4.1 on 2023-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_communication_image_communication_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='admin_message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
