# Generated by Django 4.1 on 2023-12-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_complain_admin_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='complain_available',
            new_name='assigned_to',
        ),
    ]
