# Generated by Django 4.1 on 2023-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_complain_complain_status_alter_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainsubcategory',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
