# Generated by Django 4.1 on 2023-12-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_complain_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='ticket_no',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
