# Generated by Django 4.1 on 2023-12-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nepali_name', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('headquarter', models.CharField(max_length=255)),
                ('nepali_headquarter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nepali_name', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nepali_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepalmap.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepalmap.province')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='nepalmap.province'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nepali_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepalmap.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepalmap.province')),
            ],
        ),
    ]
