# Generated by Django 4.1 on 2023-12-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepalmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='nepali_name',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='province',
        ),
    ]
