# Generated by Django 4.1 on 2023-12-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepalmap', '0002_remove_municipality_nepali_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='municipality_id',
        ),
    ]
