# Generated by Django 4.1 on 2023-12-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepalmap', '0003_remove_municipality_municipality_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipality',
        ),
    ]
